"use client"

import '@/style/globals.css'
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'

// Components
import AdminNav from "@/components/adminPanel/Navbar"
import HomeNav from "@/components/userPanel/Navbar"
import Footer from '@/components/userPanel/Footer'
import { usePathname } from 'next/navigation'
import Error from 'next/error'
 
const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Buy & Sell',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  const pathname = usePathname()

  return (
    <html lang="en">
      <body className={inter.className}>
        {pathname === "/admin"? <AdminNav/> : <HomeNav/>}
        <main>{children}</main>
        <Footer/>
      </body>
    </html>
   
  )
}
