"use client"

import '@/style/globals.css'
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'

// Components
import AdminNav from "@/components/admin/navbar"
import HomeNav from "@/components/home/navbar"
import { usePathname } from 'next/navigation'
 
const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Buy & Sell',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {

  const pathname = usePathname()
  return (
    <html lang="en">
      <body className={inter.className}>
        {pathname === "/admin"? <AdminNav/> : <HomeNav/>}
        <main>{children}</main>
      </body>
    </html>
   
  )
}
